#!/usr/bin/env bash
##
# dev-start.sh — Start local dev servers (backend + frontend with hot-reload)
#
# Uses Docker for HA, MQTT, and mock devices (infra profile), then runs the
# backend and frontend on the host with ts-node-dev and Vite respectively.
#
# Usage:
#   bash dev/scripts/dev-start.sh          # start everything
#   bash dev/scripts/dev-start.sh --skip-infra  # backend + frontend only (infra already running)
#
# Prerequisites:
#   - Docker and Docker Compose (for infra services)
#   - Node.js >=18 with npm
#   - npm ci already run in everything-presence-mmwave-configurator/
##

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEV_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
REPO_ROOT="$(cd "${DEV_DIR}/.." && pwd)"
COMPOSE_FILE="${DEV_DIR}/docker-compose.dev.yaml"
CONFIGURATOR_DIR="${REPO_ROOT}/everything-presence-mmwave-configurator"
BACKEND_DIR="${CONFIGURATOR_DIR}/backend"
BACKEND_ENV="${BACKEND_DIR}/.env"

HA_PORT="${HA_PORT:-18123}"
TOKEN_VOLUME="dev_shared-tokens"
TOKEN_FILE="/shared/ha-token"

SKIP_INFRA=false
for arg in "$@"; do
  case "$arg" in
    --skip-infra) SKIP_INFRA=true ;;
  esac
done

# ---------- Colors ----------
CYAN='\033[0;36m'
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'
log() { echo -e "${CYAN}[dev]${NC} $1"; }

# ---------- Step 1: Start infra services ----------
if [ "$SKIP_INFRA" = false ]; then
  log "Starting infra services (HA, MQTT, mock-devices)..."
  docker compose -f "$COMPOSE_FILE" up -d

  log "Waiting for ha-bootstrap to complete..."
  elapsed=0
  while [ "$elapsed" -lt 120 ]; do
    BOOTSTRAP_STATE=$(docker compose -f "$COMPOSE_FILE" ps -a --format json ha-bootstrap 2>/dev/null \
      | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('State','unknown'))" 2>/dev/null || echo "unknown")
    if [ "$BOOTSTRAP_STATE" = "exited" ]; then
      log "Bootstrap completed (${elapsed}s)"
      break
    fi
    sleep 3
    elapsed=$((elapsed + 3))
  done

  if [ "$elapsed" -ge 120 ]; then
    echo -e "${RED}[dev]${NC} Bootstrap timed out after 120s. Check: docker compose -f $COMPOSE_FILE logs ha-bootstrap"
    exit 1
  fi
else
  log "Skipping infra startup (--skip-infra)"
fi

# ---------- Step 2: Read token from Docker volume ----------
log "Reading HA token from shared volume..."
TOKEN=$(docker run --rm -v "${TOKEN_VOLUME}:${TOKEN_FILE%/*}" alpine:3.19 cat "$TOKEN_FILE" 2>/dev/null || echo "")

if [ -z "$TOKEN" ]; then
  echo -e "${RED}[dev]${NC} Could not read token from volume ${TOKEN_VOLUME}."
  echo "    Run without --skip-infra first, or check: docker compose -f $COMPOSE_FILE logs ha-bootstrap"
  exit 1
fi

log "Token obtained (${#TOKEN} chars)"

# ---------- Step 3: Write backend .env ----------
log "Writing ${BACKEND_ENV}..."
cat > "$BACKEND_ENV" <<EOF
# Auto-generated by dev-start.sh — do not commit
HA_BASE_URL=http://localhost:${HA_PORT}/api
HA_LONG_LIVED_TOKEN=${TOKEN}
PORT=42069
DATA_DIR=.data
EOF

mkdir -p "${BACKEND_DIR}/.data"
log "Backend .env ready"

# ---------- Step 4: Install deps if needed ----------
if [ ! -d "${CONFIGURATOR_DIR}/node_modules" ]; then
  log "Installing npm dependencies..."
  (cd "$CONFIGURATOR_DIR" && npm ci)
fi

# ---------- Step 5: Start dev servers ----------
log ""
log "Starting dev servers..."
log "  Backend:  http://localhost:42069  (ts-node-dev, hot-reload)"
log "  Frontend: http://localhost:5173   (Vite, HMR)"
log "  HA:       http://localhost:${HA_PORT}  (Docker)"
log ""
log "The Vite dev server proxies /api/* and /ws/* to the backend."
log "Open ${GREEN}http://localhost:5173${NC} in your browser."
log ""
log "Press Ctrl+C to stop both servers."
log ""

# Run backend and frontend concurrently; kill both on Ctrl+C
trap 'kill 0' EXIT

(cd "$BACKEND_DIR" && npm run dev) &
BACKEND_PID=$!

(cd "${CONFIGURATOR_DIR}/frontend" && npm run dev) &
FRONTEND_PID=$!

wait
